/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    markets: Market;
    cities: City;
    providers: Provider;
    territories: Territory;
    applications: Application;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    providers: {
      listedIn: 'territories';
    };
  };
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    territories: TerritoriesSelect<false> | TerritoriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The trades Earl covers. Each one becomes a /[slug]/ hub page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. Roofing
   */
  name: string;
  /**
   * URL segment. Lowercase, hyphens only — e.g. "roofing".
   */
  slug: string;
  /**
   * One sentence. Used in listings and meta descriptions.
   */
  shortDescription?: string | null;
  /**
   * Opening copy for the national /[service]/ hub page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Metro areas. Contractors buy a market, not a town.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  /**
   * e.g. Treasure Valley
   */
  name: string;
  /**
   * Internal only — markets have no page of their own.
   */
  slug: string;
  state: string;
  /**
   * Internal: coverage boundaries, pricing rationale, anything useful.
   */
  notes?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Towns with their own page. Only create one you can write real local content for.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * e.g. Boise
   */
  name: string;
  /**
   * URL segment — e.g. "boise".
   */
  slug: string;
  state: string;
  /**
   * e.g. Ada County
   */
  county?: string | null;
  lat?: number | null;
  lng?: number | null;
  /**
   * Which metro this town belongs to. Territories are sold per market, so every city in a market shares the same panel.
   */
  market: number | Market;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contractors. Vet them here before assigning a territory.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  status: 'applied' | 'vetting' | 'active' | 'paused' | 'declined';
  businessName: string;
  /**
   * URL segment for their profile page.
   */
  slug?: string | null;
  contactName?: string | null;
  phone: string;
  email: string;
  website?: string | null;
  /**
   * Their real business address. This is published as LocalBusiness schema — it must be accurate.
   */
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  licenseNumber?: string | null;
  yearsInBusiness?: number | null;
  /**
   * Re-verify before this date.
   */
  insuranceExpiry?: string | null;
  /**
   * Why Earl recommends them. This is the trust copy on the page.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?: (number | Media)[] | null;
  /**
   * Trades they work in.
   */
  services?: (number | Service)[] | null;
  /**
   * Metro areas they cover.
   */
  serviceAreas?: (number | Market)[] | null;
  /**
   * Where Earl currently lists them. Read-only. If this is empty the contractor appears nowhere on the site — open the matching Territory and add them to its Providers panel.
   */
  listedIn?: {
    docs?: (number | Territory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Internal only — never rendered on the site.
   */
  vettingNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider photos, job shots, and anything else shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * One service × one market. This is the unit a contractor buys.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territories".
 */
export interface Territory {
  id: number;
  /**
   * Generated automatically.
   */
  label?: string | null;
  status: 'live' | 'paused';
  service: number | Service;
  market: number | Market;
  /**
   * THIS is what publishes a contractor on the page. Only active providers who cover this trade and market appear here. Shown in rotating order — never ranked.
   */
  providers?: (number | Provider)[] | null;
  /**
   * How many providers we currently accept here. Once the panel is full, applicants are waitlisted.
   */
  maxProviders: number;
  /**
   * Flat USD per slot, per month.
   */
  monthlyRate?: number | null;
  /**
   * Under ~60 characters. Falls back to a generated title.
   */
  metaTitle?: string | null;
  /**
   * Under ~155 characters.
   */
  metaDescription?: string | null;
  /**
   * Opening copy for this service in this city.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The part nobody can copy: permit rules, climate, what fails here and why. Write what only someone working in this market would know.
   */
  localNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Typical job, low end (USD).
   */
  priceLow?: number | null;
  /**
   * Typical job, high end (USD).
   */
  priceHigh?: number | null;
  /**
   * Published as FAQPage schema. Four or five real questions.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contractors who want in. Approve by creating a Provider from one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  status: 'new' | 'waitlisted' | 'vetting' | 'approved' | 'declined';
  businessName: string;
  contactName?: string | null;
  phone: string;
  email: string;
  website?: string | null;
  service?: (number | null) | Service;
  city?: (number | null) | City;
  licenseNumber?: string | null;
  yearsInBusiness?: number | null;
  /**
   * Anything they told us.
   */
  message?: string | null;
  /**
   * Internal only.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every inquiry, and what happened to it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  name: string;
  phone: string;
  email?: string | null;
  zip?: string | null;
  service?: (number | null) | Service;
  city?: (number | null) | City;
  message?: string | null;
  /**
   * Who this was routed to.
   */
  provider?: (number | null) | Provider;
  /**
   * Page the form was submitted from.
   */
  sourcePage?: string | null;
  /**
   * Follow-up notes. Internal only.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin logins for Earl Knows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'territories';
        value: number | Territory;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  intro?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  state?: T;
  notes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  state?: T;
  county?: T;
  lat?: T;
  lng?: T;
  market?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  status?: T;
  businessName?: T;
  slug?: T;
  contactName?: T;
  phone?: T;
  email?: T;
  website?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  licenseNumber?: T;
  yearsInBusiness?: T;
  insuranceExpiry?: T;
  bio?: T;
  photos?: T;
  services?: T;
  serviceAreas?: T;
  listedIn?: T;
  vettingNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territories_select".
 */
export interface TerritoriesSelect<T extends boolean = true> {
  label?: T;
  status?: T;
  service?: T;
  market?: T;
  providers?: T;
  maxProviders?: T;
  monthlyRate?: T;
  metaTitle?: T;
  metaDescription?: T;
  intro?: T;
  localNotes?: T;
  priceLow?: T;
  priceHigh?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  status?: T;
  businessName?: T;
  contactName?: T;
  phone?: T;
  email?: T;
  website?: T;
  service?: T;
  city?: T;
  licenseNumber?: T;
  yearsInBusiness?: T;
  message?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  zip?: T;
  service?: T;
  city?: T;
  message?: T;
  provider?: T;
  sourcePage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}